name: Full CI quality Pipeline with Auto-commit and Qodana analysis

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - full-stack-conversion

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies on web
        run: cd web && npm ci
        working-directory: ./source

      - name: Run ESLint on web
        run: cd web &&npx eslint . --fix
        working-directory: ./source

      - name: Run Prettier on web
        run: cd web && npx prettier --write .
        working-directory: ./source

      - name: Run Stylelint on web
        run: cd web && npx stylelint "**/*.css" --fix
        working-directory: ./source

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
      
      - name: Run tests
        run: |
          cd web
          npm install
          npm run start &
          npx wait-on http://localhost:3000 --timeout 30000
          npm run test
        working-directory: ./source

  qodana:
    needs: lint-and-format # Ensure Qodana runs after linting and formatting
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A full history is required for proper analysis

      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
