name: Prettier Code

on:
  pull_request:
  push:
    branches:
      - main
      - integrate-pipeline
      - stage
      - 5-fix-cicd

permissions: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
