name: Testing

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - full-stack-conversion
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd web
          npm install
        working-directory: ./source

      - name: Start server
        run: |
          npm run start & sleep 5
        working-directory: ./source/web
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: 3000

      - name: Run tests
        run: |
          npm run test
        working-directory: ./source/web
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: 3000
